"""Add message model

Revision ID: 395aab068a9f
Revises: a37ab4d767a4
Create Date: 2025-04-17 16:06:40.044094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '395aab068a9f'
down_revision = 'a37ab4d767a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('top_artists',
               existing_type=sqlite.JSON(),
               type_=sa.PickleType(),
               existing_nullable=True)
        batch_op.alter_column('top_genres',
               existing_type=sqlite.JSON(),
               type_=sa.PickleType(),
               existing_nullable=True)
        batch_op.alter_column('recent_tracks',
               existing_type=sqlite.JSON(),
               type_=sa.PickleType(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('recent_tracks',
               existing_type=sa.PickleType(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('top_genres',
               existing_type=sa.PickleType(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('top_artists',
               existing_type=sa.PickleType(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    op.drop_table('message')
    # ### end Alembic commands ###
