"""Added top_artists, top_genres, recent_tracks to User model

Revision ID: a37ab4d767a4
Revises: 7d56f33aff0c
Create Date: 2025-04-17 15:41:21.715752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37ab4d767a4'
down_revision = '7d56f33aff0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_artists', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('top_genres', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('recent_tracks', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('recent_tracks')
        batch_op.drop_column('top_genres')
        batch_op.drop_column('top_artists')

    # ### end Alembic commands ###
